# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HNKServerFacade-Example' do

pod 'HNKServerFacade', '~> 0.1'

end

target 'HNKServerFacade-ExampleTests' do

end

