# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HNKServerFacade-Example' do

pod 'HNKServerFacade', :git => 'https://github.com/hkellaway/HNKServerFacade.git', :branch => 'feature/non-singleton'

end

target 'HNKServerFacade-ExampleTests' do

end

